const themes = []
const topicCycles = [
  {theme:"Tawakkul",themeArabic:"التوكل",surahNumber:65,ayahNumber:3,hadithCollection:"tirmidhi",hadithNumber:2344,historicalContext:"Ibrahim ﷺ was thrown into a fire by his people. Jibreel came and asked if he needed help. Ibrahim replied — I need nothing from you. His trust in Allah was so complete the fire became cool and peaceful.",reflectiveQuestion:"In what area of your life are you struggling to trust Allah completely?"},
  {theme:"Ikhlas",themeArabic:"الإخلاص",surahNumber:98,ayahNumber:5,hadithCollection:"bukhari",hadithNumber:2810,historicalContext:"Umar ibn al-Khattab would stop mid-journey to check his intentions. Once he turned back entirely because he could not purify his niyyah. His fear of showing off was greater than most people's actual worship.",reflectiveQuestion:"How much of your worship today was purely for Allah and how much was influenced by who was watching?"},
  {theme:"Sabr",themeArabic:"الصبر",surahNumber:2,ayahNumber:153,hadithCollection:"muslim",hadithNumber:918,historicalContext:"Ayyub ﷺ lost his wealth, children, and health over years of trial. He never complained to anyone except Allah. When he finally called out it was not a complaint — it was an acknowledgment. Allah restored everything and doubled it.",reflectiveQuestion:"What situation in your life right now is testing your patience?"},
  {theme:"Shukr",themeArabic:"الشكر",surahNumber:14,ayahNumber:7,hadithCollection:"muslim",hadithNumber:2999,historicalContext:"The Prophet ﷺ stood in night prayer until his feet swelled. Aisha asked why when Allah had forgiven all his sins. He replied — should I not be a grateful servant? Gratitude for him was not words — it was worship.",reflectiveQuestion:"Name three things you have today that you once made dua for."},
  {theme:"Ilm",themeArabic:"العلم",surahNumber:58,ayahNumber:11,hadithCollection:"ibnmajah",hadithNumber:224,historicalContext:"Imam Malik traveled for days to verify a single hadith. He said knowledge is not memorization — it is a light Allah places in the heart of those who are sincere.",reflectiveQuestion:"What Islamic knowledge have you gained recently and how has it changed how you act?"},
  {theme:"Tawbah",themeArabic:"التوبة",surahNumber:39,ayahNumber:53,hadithCollection:"muslim",hadithNumber:2747,historicalContext:"A man who killed 100 people sought repentance. A scholar told him nothing stands between him and tawbah. He died on the road to a righteous village and Allah forgave him based on his sincere intention.",reflectiveQuestion:"Is there something you keep delaying repentance for because you think it is too late?"},
  {theme:"Rahma",themeArabic:"الرحمة",surahNumber:21,ayahNumber:107,hadithCollection:"bukhari",hadithNumber:6011,historicalContext:"The Prophet ﷺ extended his sujood when his grandson climbed on his back during prayer. He also shortened a prayer upon hearing a baby cry so the mother would not be distressed. Mercy shaped every action.",reflectiveQuestion:"Who in your life needs your mercy right now instead of your judgment?"},
  {theme:"Adl",themeArabic:"العدل",surahNumber:4,ayahNumber:135,hadithCollection:"muslim",hadithNumber:1827,historicalContext:"Umar ibn al-Khattab was taken to a judge in a dispute with a Jewish man and lost because he could not produce a witness. He accepted the verdict. The Jewish man later accepted Islam saying he had never seen justice like it.",reflectiveQuestion:"Is there someone you have been unfair to that you need to make right with?"},
  {theme:"Sadaqa",themeArabic:"الصدقة",surahNumber:2,ayahNumber:261,hadithCollection:"bukhari",hadithNumber:1410,historicalContext:"On the day of Tabuk Abu Bakr brought everything he owned. The Prophet asked what he left for his family. He said Allah and His messenger. Umar who brought half his wealth said he would never surpass Abu Bakr.",reflectiveQuestion:"What is the most valuable thing you own that you would struggle to give for Allah?"},
  {theme:"Dhikr",themeArabic:"الذكر",surahNumber:13,ayahNumber:28,hadithCollection:"muslim",hadithNumber:2691,historicalContext:"A man told the Prophet his acts of worship were too many to maintain. The Prophet told him to keep his tongue moist with the remembrance of Allah. Dhikr requires no wudu, no direction, no time limit.",reflectiveQuestion:"How many times today did you consciously remember Allah outside of formal prayer?"},
  {theme:"Hayaa",themeArabic:"الحياء",surahNumber:33,ayahNumber:35,hadithCollection:"bukhari",hadithNumber:3484,historicalContext:"Uthman ibn Affan was known for extreme modesty. Even the angels felt shy in his presence according to the Prophet ﷺ. His hayaa extended to how he dressed, spoke, and conducted himself even in private.",reflectiveQuestion:"In what areas of your life has modesty decreased and what brought about that change?"},
  {theme:"Sidq",themeArabic:"الصدق",surahNumber:9,ayahNumber:119,hadithCollection:"bukhari",hadithNumber:6094,historicalContext:"Kab ibn Malik told the truth about missing the Battle of Tabuk when others lied. He was boycotted for 50 days. Then Allah revealed his forgiveness in the Quran. His honesty cost him greatly but earned him eternal honor.",reflectiveQuestion:"Is there a situation right now where telling the truth feels too costly?"},
  {theme:"Ukhuwwa",themeArabic:"الأخوة",surahNumber:49,ayahNumber:10,hadithCollection:"bukhari",hadithNumber:6011,historicalContext:"The Ansar of Madinah gave half their wealth and homes to the Muhajireen without being asked. One companion offered to divorce one of his wives so his Muhajir brother could marry her. That was the standard of brotherhood.",reflectiveQuestion:"When did you last sacrifice something significant for a fellow Muslim?"},
  {theme:"Dua",themeArabic:"الدعاء",surahNumber:40,ayahNumber:60,hadithCollection:"tirmidhi",hadithNumber:3370,historicalContext:"Maryam as made dua in total seclusion and Allah provided her fruit out of season. Zakariyya as made dua at an impossible age and was given Yahya. Allah answers the one who calls with sincerity and certainty.",reflectiveQuestion:"What have you stopped making dua for because it felt impossible?"},
  {theme:"Tafakkur",themeArabic:"التفكر",surahNumber:3,ayahNumber:190,hadithCollection:"tirmidhi",hadithNumber:3235,historicalContext:"The Prophet ﷺ spent long nights in prayer and reflection. Aisha asked why when Allah had forgiven everything. He said should I not be a reflecting servant. The companions valued one hour of reflection over a night of worship.",reflectiveQuestion:"When did you last sit in silence and genuinely reflect on your life and direction?"},
  {theme:"Rizq",themeArabic:"الرزق",surahNumber:11,ayahNumber:6,hadithCollection:"tirmidhi",hadithNumber:2344,historicalContext:"The Prophet ﷺ said no soul will die until it receives every provision decreed for it. Ibn al-Qayyim wrote that worrying about rizq is worrying about something already guaranteed — it shows a weakness of trust in Allah.",reflectiveQuestion:"How much of your anxiety today is about provision and how does this verse speak to that?"},
  {theme:"Mawt",themeArabic:"الموت",surahNumber:3,ayahNumber:185,hadithCollection:"tirmidhi",hadithNumber:2307,historicalContext:"Uthman ra would weep whenever he stood at a grave until his beard was wet. He said if I were between paradise and hell not knowing which way I would go I would choose to be dust before knowing. Death was always present in his heart.",reflectiveQuestion:"If you knew you had one month left what would you change about how you are living?"},
  {theme:"Akhira",themeArabic:"الآخرة",surahNumber:84,ayahNumber:6,hadithCollection:"muslim",hadithNumber:2967,historicalContext:"The Prophet ﷺ dipped his finger in the ocean and said what remains on my finger compared to the ocean is what the dunya is compared to the akhira. Everything we chase in this life is a drop. Everything we avoid for Allah is an ocean.",reflectiveQuestion:"What are you building for the akhira right now that will outlast you?"},
  {theme:"Niyyah",themeArabic:"النية",surahNumber:98,ayahNumber:5,hadithCollection:"bukhari",hadithNumber:1,historicalContext:"Umar ra said he heard the Prophet say actions are by intentions. Scholars said this single hadith contains a third of all Islamic knowledge. Every action is transformed by the intention behind it — the same deed can be worship or habit.",reflectiveQuestion:"Before your next prayer pause and consciously set your intention. What difference does it make?"},
  {theme:"Amanah",themeArabic:"الأمانة",surahNumber:33,ayahNumber:72,hadithCollection:"abudawud",hadithNumber:4944,historicalContext:"The Prophet ﷺ was known as Al-Amin before prophethood. His enemies trusted him with their valuables even as they fought him. When he left Makkah he returned everything entrusted to him before departing.",reflectiveQuestion:"Are you fully trustworthy in your private life when no one is watching?"},
  {theme:"Qanaah",themeArabic:"القناعة",surahNumber:9,ayahNumber:59,hadithCollection:"muslim",hadithNumber:1054,historicalContext:"The Prophet ﷺ said richness is not having many possessions — richness is contentment of the soul. He lived with minimal possessions yet was the most content of people. His house had no furniture except a mat and a pillow.",reflectiveQuestion:"What do you keep telling yourself you need before you can be happy?"},
  {theme:"Tawadu",themeArabic:"التواضع",surahNumber:25,ayahNumber:63,hadithCollection:"muslim",hadithNumber:2588,historicalContext:"The Prophet ﷺ would visit the sick, walk with the poor, sit on the ground, and mend his own sandals. He was the greatest of all creation yet the most humble. He forbade people from standing for him the way others stood for kings.",reflectiveQuestion:"In what areas of your life does arrogance show up even subtly?"},
  {theme:"Waqt",themeArabic:"الوقت",surahNumber:103,ayahNumber:1,hadithCollection:"bukhari",hadithNumber:6412,historicalContext:"Ibn Abbas ra said two blessings most people are deceived about — health and free time. The entire Surah Al-Asr is a warning about wasted time. Imam Shafi said if Allah had only revealed this surah it would be sufficient guidance for mankind.",reflectiveQuestion:"How much of yesterday did you spend in a way you would be proud of on the Day of Judgment?"},
  {theme:"Istiqama",themeArabic:"الاستقامة",surahNumber:41,ayahNumber:30,hadithCollection:"muslim",hadithNumber:38,historicalContext:"Abu Bakr ra was asked about istiqama. He said do not associate anything with Allah. The scholars say steadfastness of the heart is the foundation of all outward steadfastness. One consistent deed is more beloved to Allah than many inconsistent ones.",reflectiveQuestion:"What act of worship have you been inconsistent with that you want to make steady?"},
  {theme:"Hisab",themeArabic:"الحساب",surahNumber:99,ayahNumber:7,hadithCollection:"tirmidhi",hadithNumber:2417,historicalContext:"Umar ra said hold yourself accountable before you are held accountable. Weigh your deeds before they are weighed. He would review his day every night asking himself what he had done for Allah. This daily accounting kept him among the greatest.",reflectiveQuestion:"Do a 2-minute honest review of this week — more good deeds or bad?"},
  {theme:"Qiyam",themeArabic:"القيام",surahNumber:17,ayahNumber:79,hadithCollection:"muslim",hadithNumber:758,historicalContext:"The Prophet ﷺ never abandoned Qiyam al-Layl in travel or at home. Aisha said he would pray until his feet cracked. She asked why when Allah had forgiven everything. He said should I not be grateful. Gratitude expressed through the body at night.",reflectiveQuestion:"When did you last pray two rakaat in the middle of the night just for Allah?"},
  {theme:"Mahabbah",themeArabic:"المحبة",surahNumber:2,ayahNumber:165,hadithCollection:"bukhari",hadithNumber:6502,historicalContext:"Bilal ra was tortured in the burning sand of Makkah with rocks on his chest. His only words were Ahad Ahad — One One. His love for Allah made the pain insignificant. Abu Bakr eventually purchased his freedom because he could not bear to watch.",reflectiveQuestion:"What would you endure for Allah's sake — where is the limit of your love?"},
  {theme:"Khauf",themeArabic:"الخوف",surahNumber:3,ayahNumber:175,hadithCollection:"bukhari",hadithNumber:6416,historicalContext:"Yahya ibn Zakariyya as wept so much out of fear of Allah that his cheeks left permanent marks. The Prophet ﷺ said if you knew what I know you would laugh little and weep much. Healthy fear of Allah is what prevents sin.",reflectiveQuestion:"When did fear of Allah last stop you from doing something you knew was wrong?"},
  {theme:"Raja",themeArabic:"الرجاء",surahNumber:39,ayahNumber:53,hadithCollection:"bukhari",hadithNumber:7405,historicalContext:"A man on his deathbed was asked what he hoped for. He said I hope in Allah's mercy. The Prophet ﷺ said Allah says I am as My servant thinks of Me. Thinking well of Allah in the final moments is one of the greatest acts of worship.",reflectiveQuestion:"What is your honest opinion of Allah right now — do you truly believe He wants good for you?"},
  {theme:"Fitnah",themeArabic:"الفتنة",surahNumber:2,ayahNumber:286,hadithCollection:"tirmidhi",hadithNumber:2398,historicalContext:"The greater the faith the greater the trial. The prophets were tested most severely then the righteous then those like them. The companions lost family, wealth and homeland yet their faith only increased. Fitnah is not punishment — it is elevation.",reflectiveQuestion:"What trial in your life right now could be a sign of your closeness to Allah?"}
]

for (let i = 0; i < 365; i++) {
  const base = topicCycles[i % topicCycles.length]
  const cycleNum = Math.floor(i / topicCycles.length) + 1
  themes.push({
    day: i + 1,
    theme: base.theme,
    themeArabic: base.themeArabic,
    surahNumber: base.surahNumber,
    ayahNumber: base.ayahNumber,
    hadithCollection: base.hadithCollection,
    hadithNumber: base.hadithNumber,
    historicalContext: cycleNum > 1 ? base.historicalContext + " This is cycle " + cycleNum + " — revisit this theme with fresh eyes." : base.historicalContext,
    reflectiveQuestion: base.reflectiveQuestion
  })
}

const fs = require('fs')
fs.writeFileSync('src/data/dailyThemes.json', JSON.stringify(themes, null, 2))
console.log('Created 365 themes successfully')
